authentication/urls.py
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy

from . import views

urlpatterns = [
    path('', views.index_view, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),

    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/',
         PasswordChangeDoneView.as_view(template_name="authentication/password_change_done.html")),

    path('password-reset/',
         PasswordResetView.as_view(
             template_name="authentication/password_reset_form.html",
             email_template_name="authentication/password_reset_email.html",
             success_url=reverse_lazy("authentication:password_reset_done")
         ),
         name='password_reset'),

    path('password-reset/done/',
         PasswordResetDoneView.as_view(
             template_name="authentication/password_reset_done.html",
         ),
         name="password_reset_done"),

    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name="authentication/password_reset_confirm.html",
             success_url=reverse_lazy("authentication:password_reset_complete")
         ),
         name='password_reset_confirm'),

    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(
             template_name="authentication/password_reset_complete.html"
         ),
         name='password_reset_complete'),
]

dictionary/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("dict/<int:dict_id>/", views.view_dict, name="view_dict"),
    path("delete_dict/<int:dict_id>/", views.delete_dict, name="delete_dict"),
    path("add_dict/", views.add_dict, name="add_dict"),
    path("edit_dict/<int:dict_id>/", views.edit_dict, name="edit_dict")
]

dictionaryWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from schema_graph.views import Schema

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('authentication.urls', 'authentication'), namespace='authentication')),
    path('dictionary/', include(('dictionary.urls', 'dictionary'), namespace='dictionary')),
    path('word/', include(('word.urls', 'word'), namespace='word')),
    path('translation/', include(('translation.urls', 'translation'), namespace='translation')),
    path('language/', include(('language.urls', 'language'), namespace='language')),
    path("schema/", Schema.as_view()),
    path("select2/", include("django_select2.urls")),
]

language/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('view_languages/', views.view_languages, name='view_languages'),
    path('create_language/', views.create_language, name='create_language'),
    path('edit_language/<int:language_id>/', views.edit_language, name='edit_language'),
    path('delete_language/<int:language_id>/', views.delete_language, name='delete_language')
]

word/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('delete_word/<int:word_id>/', views.delete_word, name='delete_word'),
    path('create_word/<int:dictionary_id>', views.create_word, name='create_word'),
    path('update_word/<int:word_id>/', views.update_word, name='update_word'),
    path('word/<int:word_id>/', views.view_word, name='view_word')

]

authentication/models.py
from django.db import models

# Create your models here.

authentication/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.core.exceptions import ValidationError

from users.models import CustomUser


class UserLoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['email', 'password']


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 'password2', 'first_name', 'last_name']
        widgets = {'email': forms.EmailInput(attrs={'class': 'form-input'})}
        help_texts = {
            'email': 'Your email must contain @.',
        }

    def clean_email(self):
        """
        Custom validation to check for unique email addresses.
        """
        email = self.cleaned_data['email']
        if CustomUser.objects.filter(email=email).exists():
            raise ValidationError("Email address already exists. Please choose a different one.")
        return email


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Username', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(disabled=True, label='Email', widget=forms.TextInput(attrs={'class': 'form-input'}))

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'first_name', 'last_name')
        labels = {
            'first_name': 'First Name',
            'last_name': 'Last Name',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'second_name': forms.TextInput(attrs={'class': 'form-input'}),
        }


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label='Old Password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label='New Password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label='Confirm New Password',
                                    widget=forms.PasswordInput(attrs={'class': 'form-input'}))

authentication/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import UpdateView

from dictionary.models import Dictionary
from language.models import Language
from .forms import UserLoginForm, UserRegistrationForm, ProfileUserForm, PasswordChangeForm


# Create your views here.
@login_required
def index_view(request):
    source_language = request.GET.get("source_language", "")
    target_language = request.GET.get("target_language", "")

    if source_language and target_language:
        source_language_id = Language.get_by_name(source_language).id
        target_language_id = Language.get_by_name(target_language).id
        dictionaries = Dictionary.objects.filter(source_language_id=source_language_id,
                                                 target_language_id=target_language_id)
    if source_language:
        source_language_id = Language.get_by_name(source_language).id
        dictionaries = Dictionary.objects.filter(source_language_id=source_language_id)
    elif target_language:
        target_language_id = Language.get_by_name(target_language).id
        dictionaries = Dictionary.objects.filter(target_language_id=target_language_id)
    else:
        dictionaries = Dictionary.get_all()

    return render(request, "authentication/index.html",
                  {"dictionaries": dictionaries})


def login_view(request):
    if request.method == "POST":
        form = UserLoginForm(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, email=cd["email"], password=cd["password"])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('/')
                else:
                    messages.error(request, "Disabled account")
                    return render(request, "authentication/login.html", {
                        'form': form
                    })
            else:
                messages.error(request, "Incorrect email or password")
                return render(request, "authentication/login.html", {
                    'form': form
                })

    else:
        form = UserLoginForm()
    return render(request, "authentication/login.html", {'form': form})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("authentication:login"))


def register_view(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            if user:
                messages.success(request, 'Registration was successful!')
                return redirect("authentication:login")

    else:
        form = UserRegistrationForm()
    return render(request, "authentication/registration.html", {'form': form})


class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'authentication/profile.html'

    # extra_context = {'title': 'Profile'}

    def get_success_url(self):
        return reverse_lazy('authentication:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChange(PasswordChangeView):
    form_class = PasswordChangeForm
    success_url = reverse_lazy("authentication:password_change_done")
    template_name = 'authentication/password_change_form.html'

authentication/templates/authentication/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head %}
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
{% block body %}
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>

authentication/templates/authentication/index.html
{% extends "authentication/base.html" %}

{% block head %}
    <title>Main Page</title>
    <style>
        .link-offset-2 {
            color: #000000;
        }
    </style>
{% endblock %}


{% block body %}
    <div class="container">

        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Alex's main</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'language:view_languages' %}">Languages</a>
                        </li>
                        <li class="nav-item">
                            <div class="dropdown">
                                <form class="d-flex" action="{% url 'authentication:index' %}" method="get">
                                    <select class="form-select me-2" name="source_language">
                                        <option value="" selected disabled>Select Language</option>
                                        <option value="English">English</option>
                                        <option value="Russian">Russian</option>
                                        <option value="Russian">German</option>
                                    </select>
                                    <select class="form-select me-2" name="target_language">
                                        <option value="" selected disabled>Select Language</option>
                                        <option value="English">English</option>
                                        <option value="Russian">Russian</option>
                                        <option value="Russian">German</option>
                                    </select>
                                    <button class="btn btn-outline-success" type="submit">Search</button>

                                </form>
                            </div>
                        </li>
                        <li class="nav-item">
                            <div style="margin-left: 2ch">
                                <a href="/">
                                    <button class="btn btn-primary">All dicts</button>
                                </a>
                            </div>
                        </li>
                        {% if request.user.is_admin %}
                            <li class="nav-item">
                                <div style="margin-left: 2ch; ">
                                    <a href="{% url 'dictionary:add_dict' %}">
                                        <button class="btn btn-primary">Add new</button>
                                    </a>
                                </div>
                            </li>
                        {% endif %}
                    </ul>
                    <a href="{% url 'authentication:profile' %}" class="nav-link active" ,
                       style="margin-right: 1%">{{ request.user.username }}</a>
                    <a href="{% url 'authentication:logout' %}">
                        <button type="submit" class="btn btn-primary">Log Out</button>
                    </a>

                </div>
            </div>

        </nav>

        <h1>Welcome, {{ request.user.first_name }}</h1>
        <br>
        <ul class="list-group">
            {% for dictionary in dictionaries %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <a class="link-offset-2 link-underline link-underline-opacity-0"
                       href="{% url 'dictionary:view_dict' dictionary.id %}">
                        <div class="ms-2 me-auto">
                            <div class="fw-bold">{{ dictionary.name }}</div>
                            {{ dictionary.source_language }} -> {{ dictionary.target_language }}

                        </div>
                    </a>
                    {% if request.user.is_admin %}
                        <a href="{% url 'dictionary:delete_dict' dictionary.id %}">
                            <button class="btn btn-primary">Delete</button>
                        </a>
                    {% endif %}
                </li>
                <br>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

authentication/templates/authentication/login.html
{% extends "authentication/base.html" %}

{% block head %}
    <title>Log In</title>
    <style>
        .container {
            max-width: 500px;
            margin: 50px auto;
            text-align: center;
        }

        ul {
            list-style: none;
            padding: 0;
        }

        li {
            margin-bottom: 10px;
            font-size: 12px;
        }

        .errorlist {
            text-align: center;
            margin-bottom: 20px;
            color: red;
        }

        .error {
            text-align: center;
            margin-bottom: 20px;
            color: red;
        }

        .success {
            text-align: center;
            margin-bottom: 20px;
            color: green;
        }
    </style>
{% endblock %}

{% block body %}

    <div class="container">
        <form method="post">
            <h1 id="title">Log In</h1>
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li id="message" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            {% if error %}
                <h2 id="error">{{ error }}</h2>
            {% endif %}

            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Log In</button>
            <a href="{% url 'authentication:register' %}">
                <button type="button" class="btn btn-primary">Register</button>
            </a>
            <a href="{% url 'authentication:password_reset' %}">
                <button type="button" class="btn btn-primary">Forgot password</button>
            </a>
        </form>

    </div>

{% endblock %}

authentication/templates/authentication/password_change_done.html
{% extends "authentication/base.html" %}

{% block head %}
    <title> Profile </title>
    <style>
        .container {
            /*display: flex;*/
            justify-content: center;
            align-items: center;
            text-align: center;
        }
    </style>

{% endblock %}

{% block body %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Alex's main</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                </ul>

            </div>
        </div>
    </nav>
    <div class="container">
        <h1>Password is updated successfully!</h1>
        <p>You've changed your password. <a href="{% url 'authentication:profile' %}">Return to profile.</a>
        <p>
    </div>
{% endblock %}

authentication/templates/authentication/password_change_form.html
{% extends "authentication/base.html" %}

{% block head %}
    <title> Profile </title>
    <style>
        .container {
            display: flex;
            justify-content: center;
            align-items: center;
        }
    </style>

{% endblock %}

{% block body %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Alex's main</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                </ul>

            </div>
        </div>
    </nav>
    <div class="container">
        <form method="post">
            <h1 id="title">Password Change</h1>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Change password</button>
            <hr>
        </form>
    </div>
{% endblock %}

authentication/templates/authentication/password_reset_complete.html
{% extends "authentication/base.html" %}

{% block head %}
    <title> Profile </title>
    <style>
        .container {
            text-align: center;
            justify-content: center;
            align-items: center;
        }
    </style>

{% endblock %}

{% block body %}
    <div class="container">
        <h1 id="title">Password changed</h1>
        <p>Congrats! We changed the password successfully. Use it for
            <a href="{% url 'authentication:login' %}">log into the system </a></p>
    </div>
{% endblock %}

authentication/templates/authentication/password_reset_confirm.html
{% extends "authentication/base.html" %}

{% block head %}
    <title> Profile </title>
    <style>
        .container {
            display: flex;
            justify-content: center;
            align-items: center;
        }
    </style>

{% endblock %}

{% block body %}
    <div class="container">
        <form method="post">
            <h1 id="title">New password</h1>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
{% endblock %}

authentication/templates/authentication/password_reset_done.html
{% extends "authentication/base.html" %}
{% load i18n %}

{% block head %}
    <title> Profile </title>
    <style>
        .container {
            justify-content: center;
            align-items: center;
            text-align: center;
        }
    </style>

{% endblock %}

{% block body %}
    <div class="container">
        <h1 id="title">Recovering password</h1>
        <p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>
        <p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>
    </div>

{% endblock %}

authentication/templates/authentication/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at
    {{ site_name }}.{% endblocktranslate %}
{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
    {{ protocol }}://{{ domain }}{% url 'authentication:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

authentication/templates/authentication/password_reset_form.html
{% extends "authentication/base.html" %}

{% block head %}
    <title> Profile </title>
    <style>
        .container {
            display: flex;
            margin: 50px auto;
            text-align: center;
            justify-content: center;
            align-items: center;
        }
    </style>

{% endblock %}

{% block body %}
    <div class="container">

        <form method="post">
            <h1 id="title">Recovering password</h1>
            {% csrf_token %}
            {{ form.as_p }}
            <p>
                <button type="submit" class="btn btn-primary">Send with email</button>
            </p>
        </form>
    </div>

{% endblock %}

authentication/templates/authentication/profile.html
{% extends "authentication/base.html" %}

{% block head %}
    <title> Profile </title>
    <style>
        form {
            text-align: center;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Alex's main</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'language:view_languages' %}">Languages</a>
                        </li>
                    </ul>
                    <a href="{% url 'authentication:profile' %}" class="nav-link active" ,
                       style="margin-right: 1%">{{ request.user.username }}</a>
                    <a href="{% url 'authentication:logout' %}">
                        <button type="submit" class="btn btn-primary">Log Out</button>
                    </a>
                </div>
            </div>
        </nav>


        <form method="post">
            <h1 id="title">Profile</h1>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Save</button>
            <hr>
            <a href="{% url 'authentication:password_change' %}">
                <button type="button" class="btn btn-primary">Change password</button>
            </a>
        </form>


    </div>
{% endblock %}

authentication/templates/authentication/registration.html
{% extends "authentication/base.html" %}

{% block head %}
    <title> Registration </title>
    <style>
        .container {
            display: flex;
            justify-content: center;
            align-items: center;
        }
    </style>

{% endblock %}

{% block body %}
    <div class="container">
        <form method="post">
            <h1 id="title">Registration</h1>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Register</button>
            <br><br>
            <a href="{% url 'authentication:login' %}">
                <button type="button" class="btn btn-primary">Log In</button>
            </a>
        </form>
    </div>
{% endblock %}