dictionaryWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from schema_graph.views import Schema

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('authentication.urls', 'authentication'), namespace='authentication')),
    path('dictionary/', include(('dictionary.urls', 'dictionary'), namespace='dictionary')),
    path('word/', include(('word.urls', 'word'), namespace='word')),
    path('translation/', include(('translation.urls', 'translation'), namespace='translation')),
    path('language/', include(('language.urls', 'language'), namespace='language')),
    path("schema/", Schema.as_view()),
    path("select2/", include("django_select2.urls")),
]

translation/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('create_translation/<int:word_id>/', views.create_translation, name='create_translation'),
    path('update_translation/<int:translation_id>/', views.update_translation, name='update_translation'),
    path('delete_translation/<int:translation_id>/', views.delete_translation, name='delete_translation')
]

word/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('delete_word/<int:word_id>/', views.delete_word, name='delete_word'),
    path('create_word/<int:dictionary_id>', views.create_word, name='create_word'),
    path('update_word/<int:word_id>/', views.update_word, name='update_word'),
    path('word/<int:word_id>/', views.view_word, name='view_word')

]

word/models.py
from django.db import models

from language.models import Language
from translation.models import Translation


# Create your models here.
class Word(models.Model):
    text = models.CharField(max_length=100)
    language = models.ForeignKey(Language, on_delete=models.CASCADE)
    translations = models.ManyToManyField(Translation, related_name='translations')

    class Meta:
        db_table = 'words'
        verbose_name = 'Word'
        verbose_name_plural = 'Words'

    def __str__(self):
        return f"{self.text}"

    @staticmethod
    def get_by_id(word_id):
        """
        :param word_id: SERIAL: the id of a Word to be found in the DB
        :return: Word object or None if a word with such ID does not exist
        """
        return Word.objects.get(id=word_id) if Word.objects.filter(id=word_id) else None

    @staticmethod
    def delete_by_id(word_id):
        """
        :param word_id: an id of a translation to be deleted
        :type word_id: int
        :return: True if object existed in the db and was removed or False if it didn't exist
        """
        if Word.get_by_id(word_id) is None:
            return False
        Word.objects.get(id=word_id).delete()
        return True

    @staticmethod
    def get_all():
        """
        returns data for json request with QuerySet of all translations
        """
        return list(Word.objects.all())

    def add_translation(self, translation):
        """
        Add a translation to the word in database
        :param translation: translation
        """
        self.translations.add(translation)
        self.save()

    def remove_translation(self, translation):
        """
        Remove a translation to the word in database
        :param translation: translation
        """
        self.translations.remove(translation)

word/forms.py
from django import forms
from django_select2 import forms as s2forms

from translation.models import Translation
from .models import Word


class TranslationsWidget(s2forms.ModelSelect2MultipleWidget):
    search_fields = ('text__icontains',)


class WordForm(forms.ModelForm):
    translations = forms.ModelMultipleChoiceField(queryset=Translation.objects, required=False,
                                                  widget=TranslationsWidget)

    class Meta:
        model = Word
        fields = '__all__'


class WordEditForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(WordEditForm, self).__init__(*args, **kwargs)
        instance = kwargs.get('instance')
        if instance:
            self.fields['text'].initial = instance.text
            self.fields['text'].disabled = True
            self.fields['language'].initial = instance.language
            self.fields['language'].disabled = True
            self.fields['translations'].queryset = Translation.objects.all()
            self.fields['translations'].initial = instance.translations.all()

    class Meta:
        model = Word
        fields = '__all__'
        widgets = {
            'translations': TranslationsWidget,
        }

word/views.py
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render, redirect

from dictionary.models import Dictionary
from .forms import WordForm, WordEditForm
from .models import Word


# Create your views here.
def is_admin_user(user):
    return user.is_admin


@user_passes_test(is_admin_user)
def delete_word(request, word_id):
    if request.method == 'POST':
        Word.delete_by_id(word_id)
        return redirect("authentication:index")
    return render(request, 'word/delete.html')


@user_passes_test(is_admin_user)
def create_word(request, dictionary_id):
    dictionary = Dictionary.get_by_id(dictionary_id)
    if request.method == 'POST':
        form = WordForm(request.POST)
        if form.is_valid():
            word = form.save()
            dictionary.words.add(word)
            return redirect("dictionary:view_dict", dict_id=dictionary.id)
    else:
        form = WordForm()
        return render(request, 'word/create_word.html',
                      {'form': form})


@user_passes_test(is_admin_user)
def update_word(request, word_id):
    word = Word.get_by_id(word_id)

    if request.method == 'POST':
        form = WordEditForm(request.POST, instance=word)
        if form.is_valid():
            form.save()
            return redirect('word:view_word', word_id=word_id)

    form = WordEditForm(instance=word)
    return render(request, 'word/edit_word.html',
                  {'form': form})


def view_word(request, word_id):
    request_query = request.GET.get('search', '')
    word = Word.get_by_id(word_id)
    translations = word.translations.filter(text__icontains=request_query)
    return render(request, 'word/view_word.html',
                  {'word': word,
                   'translations': translations})

word/templates/word/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head %}
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
{% block body %}
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>

word/templates/word/create_word.html
{% extends "word/base.html" %}

{% block head %}
    <title>Words</title>
    {{ form.media.css }}
    <style>

        select[name="translations"] {
            width: 100%;
            height: 30%
        }
    </style>
{% endblock %}

{% block body %}

    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Alex's main</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">Home</a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>


        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        {{ form.media.js }}
    </div>

{% endblock %}

word/templates/word/delete.html
{% extends "word/base.html" %}

{% block head %}
    <title>Words</title>
{% endblock %}


{% block body %}

    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Alex's main</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">Home</a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>

        <div class="container">
            <h1>Confirm Delete Word</h1>
            <h2>Are you sure you want to delete this word?</h2>
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">Delete</button>
            </form>
        </div>
    </div>
{% endblock %}

word/templates/word/edit_word.html
{% extends "word/base.html" %}

{% block head %}
    <title>Words</title>
    {{ form.media.css }}
    <style>
        select[name="translations"] {
            width: 100%;
            height: 30%
        }
    </style>
{% endblock %}

{% block body %}

    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Alex's main</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">Home</a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>


        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        {{ form.media.js }}
    </div>

{% endblock %}

word/templates/word/view_word.html
{% extends "word/base.html" %}

{% block head %}
    <title>Words</title>
    <style>
        .btn-primary {
            margin-top: 10px;
        }

        .link-offset-2 {
            color: #000000;
        }

        .buttons {
            margin-left: auto;
        }
    </style>

{% endblock %}


{% block body %}

    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Alex's main</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">Home</a>
                        </li>
                    </ul>

                    <form class="d-flex" action="{% url 'word:view_word' word.id %}" method="get">
                        <input class="form-control me-2" name="search" type="search" placeholder="Search"
                               aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
        <div class="row">
            <div class="col">
                <h1>Word: "{{ word.text }}"</h1>
            </div>

            <div class="col">
                <a href="{% url 'word:view_word' word.id %}">
                    <button class="btn btn-primary">All translations</button>
                </a>
                {% if request.user.is_admin %}
                    <a href="{% url 'word:update_word' word.id %}">
                        <button class="btn btn-primary">Update</button>
                    </a>
                    <a href="{% url 'translation:create_translation' word.id %}">
                        <button class="btn btn-primary">Create translation</button>
                    </a>
                {% endif %}
            </div>

        </div>
        <h2>Translations:</h2>

        <ul class="list-group">
            {% for translation in translations %}
                <a class="link-offset-2 link-underline link-underline-opacity-0" href="">
                    <li class="list-group-item d-flex justify-content-between ">
                        <div class="ms-2 me-auto">
                            <div class="fw-bold">{{ translation }}</div>
                        </div>
                        {% if request.user.is_admin %}
                            <div class="buttons">
                                <a class="link-offset-2 link-underline link-underline-opacity-0"
                                   href="{% url 'translation:update_translation' translation.id %}">
                                    <button class="btn btn-primary">Update</button>
                                </a>
                                <a class="link-offset-2 link-underline link-underline-opacity-0"
                                   href="{% url 'translation:delete_translation' translation.id %}">
                                    <button class="btn btn-primary">Delete</button>
                                </a>
                            </div>
                        {% endif %}
                    </li>
                </a><br>
            {% endfor %}
        </ul>
    </div>
{% endblock %}