authentication/urls.py
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy

from . import views

urlpatterns = [
    path('', views.index_view, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),

    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/',
         PasswordChangeDoneView.as_view(template_name="authentication/password_change_done.html")),

    path('password-reset/',
         PasswordResetView.as_view(
             template_name="authentication/password_reset_form.html",
             email_template_name="authentication/password_reset_email.html",
             success_url=reverse_lazy("authentication:password_reset_done")
         ),
         name='password_reset'),

    path('password-reset/done/',
         PasswordResetDoneView.as_view(
             template_name="authentication/password_reset_done.html",
         ),
         name="password_reset_done"),

    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name="authentication/password_reset_confirm.html",
             success_url=reverse_lazy("authentication:password_reset_complete")
         ),
         name='password_reset_confirm'),

    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(
             template_name="authentication/password_reset_complete.html"
         ),
         name='password_reset_complete'),
]

dictionary/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("dict/<int:dict_id>/", views.view_dict, name="view_dict"),
    path("delete_dict/<int:dict_id>/", views.delete_dict, name="delete_dict"),
    path("add_dict/", views.add_dict, name="add_dict"),
    path("edit_dict/<int:dict_id>/", views.edit_dict, name="edit_dict")
]

dictionaryWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from schema_graph.views import Schema

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('authentication.urls', 'authentication'), namespace='authentication')),
    path('dictionary/', include(('dictionary.urls', 'dictionary'), namespace='dictionary')),
    path('word/', include(('word.urls', 'word'), namespace='word')),
    path('translation/', include(('translation.urls', 'translation'), namespace='translation')),
    path('language/', include(('language.urls', 'language'), namespace='language')),
    path("schema/", Schema.as_view()),
    path("select2/", include("django_select2.urls")),
]

word/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('delete_word/<int:word_id>/', views.delete_word, name='delete_word'),
    path('create_word/<int:dictionary_id>', views.create_word, name='create_word'),
    path('update_word/<int:word_id>/', views.update_word, name='update_word'),
    path('word/<int:word_id>/', views.view_word, name='view_word')

]

dictionary/models.py
from django.db import models
from language.models import Language
from word.models import Word


# Create your models here.
class Dictionary(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=200, blank=True)
    source_language = models.ForeignKey(Language, related_name='source_dicts', on_delete=models.CASCADE)
    target_language = models.ForeignKey(Language, related_name='target_dicts', on_delete=models.CASCADE)
    words = models.ManyToManyField(Word, related_name='dictionaries')

    class Meta:
        db_table = 'dictionaries'
        verbose_name = 'Dictionary'
        verbose_name_plural = 'Dictionaries'

    @staticmethod
    def get_by_id(dict_id):
        """
        :param dict_id: SERIAL: the id of a Dictionary to be found in the DB
        :return: dictionary object or None if a dictionary with such ID does not exist
        """
        return Dictionary.objects.get(id=dict_id) if Dictionary.objects.filter(id=dict_id) else None

    @staticmethod
    def get_all():
        """
        returns data for json request with QuerySet of all dictionaries
        """
        return list(Dictionary.objects.all())

    @staticmethod
    def delete_by_id(dict_id):
        """
        :param dict_id: an id of a dictionary to be deleted
        :type dict_id: int
        :return: True if object existed in the db and was removed or False if it didn't exist
        """
        if Dictionary.get_by_id(dict_id) is None:
            return False
        Dictionary.objects.get(id=dict_id).delete()
        return True

    def get_words(self):
        """
        return all words in the dictionary sorted alphabetically
        """
        return self.words.order_by('text')

    def add_word(self, word):
        """
        Add a word to the dictionary in database
        :param word: word
        """
        self.words.add(word)
        self.save()

    def remove_word(self, word):
        """
        Remove a word to the dictionary in database
        :param word: word
        """
        self.words.remove(word)

dictionary/forms.py
from django import forms
from .models import Dictionary
from django_select2 import forms as s2forms
from word.models import Word


class WordsWidget(s2forms.ModelSelect2MultipleWidget):
    search_fields = ('text__icontains',)


class DictionaryForm(forms.ModelForm):
    # words = forms.ModelMultipleChoiceField(
    #     queryset=Word.objects.all(),
    #     widget=forms.CheckboxSelectMultiple(attrs={'class': 'form'}),
    #     label="Words",
    #     required=False
    # )
    def __init__(self, *args, **kwargs):
        super(DictionaryForm, self).__init__(*args, **kwargs)
        self.fields['words'].required = False

    class Meta:
        model = Dictionary
        fields = "__all__"
        widgets = {
            "words": WordsWidget,
        }


class DictionaryEditForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(DictionaryEditForm, self).__init__(*args, **kwargs)
        instance = kwargs.get('instance')
        if instance:
            self.fields['name'].initial = instance.name
            self.fields['description'].initial = instance.description
            self.fields['source_language'].initial = instance.source_language
            self.fields['target_language'].initial = instance.target_language
            self.fields['words'].queryset = Word.objects.all()
            self.fields['words'].initial = instance.words.all()

    class Meta:
        model = Dictionary
        fields = "__all__"
        widgets = {
            "words": WordsWidget,
        }

dictionary/views.py
from django.shortcuts import render, redirect
from .models import Dictionary
from .forms import DictionaryForm, DictionaryEditForm
from django.contrib.auth.decorators import user_passes_test


def is_admin_user(user):
    return user.is_admin


# Create your views here.
def view_dict(request, dict_id):
    dictionary = Dictionary.get_by_id(dict_id)
    words = dictionary.get_words()

    search_query = request.GET.get('search', '')
    if search_query:
        words = words.filter(text__icontains=search_query)

    return render(request, 'dictionary/view_dict.html',
                  {'dictionary': dictionary,
                   'words': words}
                  )


@user_passes_test(is_admin_user)
def delete_dict(request, dict_id):
    if request.method == 'POST':
        Dictionary.delete_by_id(dict_id)
        return redirect("authentication:index")
    return render(request, 'dictionary/delete_dict.html')


@user_passes_test(is_admin_user)
def add_dict(request):
    if request.method == 'POST':
        form = DictionaryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("authentication:index")
    else:
        form = DictionaryForm()
    return render(request, "dictionary/add.html", {
        'form': form
    })


@user_passes_test(is_admin_user)
def edit_dict(request, dict_id):
    dictionary = Dictionary.get_by_id(dict_id)
    if request.method == 'POST':
        form = DictionaryEditForm(request.POST, instance=dictionary)
        if form.is_valid():
            form.save()
            return redirect(f'dictionary:view_dict', dict_id=dict_id)

    else:
        form = DictionaryEditForm(instance=dictionary)
    return render(request, 'dictionary/edit.html', {
        'form': form
    })

dictionary/templates/dictionary/add.html
{% extends "dictionary/base.html" %}

{% block head %}
    <title>Dictionaries</title>
    {{ form.media.css }}
    <style>

        select[name="words"] {
            width: 100%;
            height: 30%
        }
    </style>


{% endblock %}


{% block body %}

    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Alex's main</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">Home</a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>

        <h1>Add new dictionary</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <br><br>
            <button class="btn btn-primary" type="submit">Add Dictionary</button>
        </form>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        {{ form.media.js }}
    </div>

{% endblock %}

dictionary/templates/dictionary/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head %}
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
{% block body %}
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>

dictionary/templates/dictionary/delete_dict.html
{% extends "dictionary/base.html" %}

{% block head %}
    <title>Dictionaries</title>

{% endblock %}


{% block body %}

    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Alex's main</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">Home</a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>

        <div class="container">
            <h1>Confirm Delete Book</h1>
            <h2>Are you sure you want to delete this dictionary?</h2>
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">Delete</button>
            </form>
        </div>
    </div>
{% endblock %}

dictionary/templates/dictionary/edit.html
{% extends "dictionary/base.html" %}

{% block head %}
    <title>Dictionaries</title>
    {{ form.media.css }}
    <style>
        input, select {
            width: 50%;
        }

        select[name="words"] {
            width: 100%;
        }

    </style>


{% endblock %}


{% block body %}

    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Alex's main</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">Home</a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>

        <h1>Update dictionary</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <br><br>
            <button class="btn btn-primary" type="submit">Update dictionary</button>
        </form>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        {{ form.media.js }}
    </div>

{% endblock %}

dictionary/templates/dictionary/view_dict.html
{% extends "dictionary/base.html" %}

{% block head %}
    <title>Dictionaries</title>
    <style>

        .link-offset-2 {
            color: #000000;
        }

        .buttons {
            margin-left: auto;
        }
    </style>

{% endblock %}


{% block body %}

    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Alex's main</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">Home</a>
                        </li>
                    </ul>

                    <form class="d-flex" action="{% url 'dictionary:view_dict' dictionary.id %}" method="get">
                        <input class="form-control me-2" name="search" type="search" placeholder="Search"
                               aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                    <div style="margin: 1ch">
                        <a href="{% url 'authentication:profile' %}"
                           class="nav-link active">{{ request.user.username }}</a>
                    </div>

                    <a href="{% url 'authentication:logout' %}">
                        <button type="submit" class="btn btn-primary">Log Out</button>
                    </a>
                </div>
            </div>
        </nav>
        <div class="container">
            <div class="row">
                <div class="col">
                    <h1>Dictionary: "{{ dictionary.name }}"</h1>
                </div>
                <div class="col">
                    <a href="{% url 'dictionary:view_dict' dictionary.id %}">
                        <button class="btn btn-primary">All words</button>
                    </a>
                    {% if request.user.is_admin %}
                        <a href="{% url 'dictionary:edit_dict' dictionary.id %}">
                            <button class="btn btn-primary">Update</button>
                        </a>
                        <a href="{% url 'word:create_word' dictionary.id %}">
                            <button class="btn btn-primary">Create word</button>
                        </a>
                    {% endif %}
                </div>
            </div>
            <h2>Description</h2>
            <p> {{ dictionary.description }}</p>
            <ul class="list-group">
                {% for word in words %}
                    <a class="link-offset-2 link-underline link-underline-opacity-0"
                       href="{% url 'word:view_word' word.id %}">
                        <li class="list-group-item d-flex justify-content-between ">
                            <div class="ms-2 me-auto">
                                <div class="fw-bold">{{ word }}</div>
                                {% for translation in word.translations.all %}
                                    {{ translation.text }}
                                    {% if forloop.last %}
                                        {% if not word.translations.all %}
                                            .
                                        {% else %}
                                            .
                                        {% endif %}
                                    {% else %}
                                        ,
                                    {% endif %}
                                {% endfor %}
                            </div>
                            {% if request.user.is_admin %}
                                <div class="buttons">
                                    <a class="link-offset-2 link-underline link-underline-opacity-0"
                                       href="{% url 'word:delete_word' word.id %}">
                                        <button class="btn btn-primary">Delete</button>
                                    </a>
                                </div>
                            {% endif %}
                        </li>
                    </a><br>
                {% endfor %}
            </ul>
        </div>
{% endblock %}