dictionaryWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from schema_graph.views import Schema

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('authentication.urls', 'authentication'), namespace='authentication')),
    path('dictionary/', include(('dictionary.urls', 'dictionary'), namespace='dictionary')),
    path('word/', include(('word.urls', 'word'), namespace='word')),
    path('translation/', include(('translation.urls', 'translation'), namespace='translation')),
    path('language/', include(('language.urls', 'language'), namespace='language')),
    path("schema/", Schema.as_view()),
    path("select2/", include("django_select2.urls")),
]

language/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('view_languages/', views.view_languages, name='view_languages'),
    path('create_language/', views.create_language, name='create_language'),
    path('edit_language/<int:language_id>/', views.edit_language, name='edit_language'),
    path('delete_language/<int:language_id>/', views.delete_language, name='delete_language')
]

word/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('delete_word/<int:word_id>/', views.delete_word, name='delete_word'),
    path('create_word/<int:dictionary_id>', views.create_word, name='create_word'),
    path('update_word/<int:word_id>/', views.update_word, name='update_word'),
    path('word/<int:word_id>/', views.view_word, name='view_word')

]

language/models.py
from django.db import models


class Language(models.Model):
    """
    This class represents a Language. \n
    Attributes:
    """
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=10)

    class Meta:
        db_table = 'languages'
        verbose_name = 'Language'
        verbose_name_plural = 'Languages'

    def __str__(self):
        """
        Magic method is redefined to show information about this Language
        :return: language name
        """
        return f"{self.name}"

    def __repr__(self):
        """
        Magic method is redefined to show information about class and id of Language object
        :return: class, language id
        """
        return f"Language: {self.id}"

    @staticmethod
    def get_by_id(lang_id):
        """
        :param lang_id: SERIAL: the id of a Language to be found in the DB
        :return: language object or None if a language with such ID does not exist
        """
        return Language.objects.get(id=lang_id) if Language.objects.filter(id=lang_id) else None

    @staticmethod
    def get_by_name(lang_name):
        """
        :param lang_name: SERIAL: the name of a Language to be found in the DB
        :return: language object or None if a language with such Name does not exist
        """
        return Language.objects.get(name=lang_name) if Language.objects.filter(name=lang_name) else None

    @staticmethod
    def delete_by_id(lang_id):
        """
        :param lang_id: an id of a language to be deleted
        :type lang_id: int
        :return: True if object existed in the db and was removed or False if it didn't exist
        """
        if Language.get_by_id(lang_id) is None:
            return False
        Language.objects.get(id=lang_id).delete()
        return True

    @staticmethod
    def get_all():
        """
        returns data for json request with QuerySet of all languages
        """
        return list(Language.objects.all())

language/forms.py
from django import forms

from language.models import Language


class LanguageForm(forms.ModelForm):
    class Meta:
        model = Language
        fields = '__all__'


class LanguageEditForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(LanguageEditForm, self).__init__(*args, **kwargs)
        instance = kwargs.pop('instance')
        if instance:
            self.fields['name'].initial = instance.name

    class Meta:
        model = Language
        fields = '__all__'

language/views.py
from django.shortcuts import render, redirect

from language.models import Language
from .forms import LanguageForm, LanguageEditForm


# Create your views here.
def view_languages(request):
    languages = Language.objects.all()
    search_query = request.GET.get('search', '')
    if search_query:
        languages = languages.filter(name__icontains=search_query)
    return render(request, 'language/view_languages.html',
                  {'languages': languages})


def create_language(request):
    if request.method == 'POST':
        form = LanguageForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('language:view_languages')
    form = LanguageForm()
    return render(request, 'language/create_language.html', {'form': form})


def edit_language(request, language_id):
    language = Language.get_by_id(language_id)
    if request.method == 'POST':
        form = LanguageEditForm(request.POST, instance=language)
        if form.is_valid():
            form.save()
            return redirect('language:view_languages')
    form = LanguageEditForm(instance=language)
    return render(request, 'language/edit_language.html', {'form': form})


def delete_language(request, language_id):
    if request.method == 'POST':
        Language.delete_by_id(language_id)
        return redirect('language:view_languages')
    return render(request, 'language/delete_language.html')

language/templates/language/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head %}
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
{% block body %}
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>

language/templates/language/create_language.html
{% extends "language/base.html" %}

{% block head %}
    <title>Languages</title>
    <style>
        form {
            text-align: center;
        }
    </style>
{% endblock %}

{% block body %}

    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Alex's main</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">Home</a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>


        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Create</button>
        </form>

    </div>

{% endblock %}

language/templates/language/delete_language.html
{% extends "language/base.html" %}

{% block head %}
    <title>Languages</title>
{% endblock %}


{% block body %}

    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Alex's main</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">Home</a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>

        <div class="container">
            <h1>Confirm Delete Language</h1>
            <h2>Are you sure you want to delete this language?</h2>
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">Delete</button>
            </form>
        </div>
    </div>
{% endblock %}

language/templates/language/edit_language.html
{% extends "language/base.html" %}

{% block head %}
    <title>Languages</title>
    <style>
        form {
            text-align: center;
        }
    </style>
{% endblock %}

{% block body %}

    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Alex's main</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">Home</a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>


        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Update</button>
        </form>

    </div>

{% endblock %}

language/templates/language/view_languages.html
{% extends 'language/base.html' %}

{% block head %}
    <title>Languages</title>

{% endblock %}

{% block body %}

    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Alex's main</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">Home</a>
                        </li>
                    </ul>

                    <form class="d-flex" action="{% url 'language:view_languages' %}" method="get">
                        <input class="form-control me-2" name="search" type="search" placeholder="Search"
                               aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
        <div class="row">
            <div class="col">
                <h1>All Languages: </h1>
            </div>
            <div class="col">
                <a href="{% url 'language:view_languages' %}">
                    <button class="btn btn-primary">All languages</button>
                </a>
                {% if request.user.is_admin %}
                    <a href="{% url 'language:create_language' %}">
                        <button class="btn btn-primary">Create language</button>
                    </a>
                {% endif %}
            </div>

        </div>
        <ul class="list-group">
            {% for language in languages %}
                <li class="list-group-item d-flex justify-content-between ">
                    <div class="ms-2 me-auto">
                        <div class="fw-bold">{{ language.name }}</div>

                    </div>
                    {% if request.user.is_admin %}
                        <div class="buttons">
                            <a class="link-offset-2 link-underline link-underline-opacity-0"
                               href="{% url 'language:edit_language' language.id %}">
                                <button class="btn btn-primary">Update</button>
                            </a>
                            <a class="link-offset-2 link-underline link-underline-opacity-0"
                               href="{% url 'language:delete_language' language.id %}">
                                <button class="btn btn-primary">Delete</button>
                            </a>
                        </div>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}